// This file is generated by scripts/fetch-tools.ts. Do not edit by hand.
export const TOOL_CATALOG = [
  {
    "name": "playwright",
    "description": "A high-level API to automate web browsers",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "puppeteer",
    "description": "A high-level API to control headless Chrome over the DevTools Protocol",
    "keywords": [
      "puppeteer",
      "chrome",
      "headless",
      "automation"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "vitest",
    "description": "Next generation testing framework powered by Vite",
    "keywords": [
      "vite",
      "vitest",
      "test",
      "jest"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "jest",
    "description": "Delightful JavaScript Testing.",
    "keywords": [
      "ava",
      "babel",
      "coverage",
      "easy",
      "expect",
      "facebook",
      "immersive",
      "instant",
      "jasmine",
      "jest",
      "jsdom",
      "mocha",
      "mocking",
      "painless",
      "qunit",
      "runner",
      "sandboxed",
      "snapshot",
      "tap",
      "tape",
      "test",
      "testing",
      "typescript",
      "watch"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "axios",
    "description": "Promise based HTTP client for the browser and node.js",
    "keywords": [
      "xhr",
      "http",
      "ajax",
      "promise",
      "node"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@tanstack/react-query",
    "description": "Hooks for managing, caching and syncing asynchronous and remote data in React",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "jotai",
    "description": "👻 Primitive and flexible state management for React",
    "keywords": [
      "react",
      "state",
      "manager",
      "management",
      "recoil",
      "store"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "zustand",
    "description": "🐻 Bear necessities for state management in React",
    "keywords": [
      "react",
      "state",
      "manager",
      "management",
      "redux",
      "store"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "swr",
    "description": "React Hooks library for remote data fetching",
    "keywords": [
      "swr",
      "react",
      "hooks",
      "request",
      "cache",
      "fetch"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "next",
    "description": "The React Framework",
    "keywords": [
      "react",
      "framework",
      "nextjs",
      "web",
      "server",
      "node",
      "front-end",
      "backend",
      "cli",
      "vercel"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react",
    "description": "React is a JavaScript library for building user interfaces.",
    "keywords": [
      "react"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "vite",
    "description": "Native-ESM powered web dev build tool",
    "keywords": [
      "frontend",
      "framework",
      "hmr",
      "dev-server",
      "build-tool",
      "vite"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "webpack",
    "description": "Packs ECMAScript/CommonJs/AMD modules for the browser. Allows you to split your codebase into multiple bundles, which can be loaded on demand. Supports loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-is",
    "description": "Brand checking of React Elements.",
    "keywords": [
      "react"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-smooth",
    "description": "react animation library",
    "keywords": [
      "react",
      "reactjs",
      "animation",
      "react-component"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-router",
    "description": "Declarative routing for React",
    "keywords": [
      "react",
      "router",
      "route",
      "routing",
      "history",
      "link"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@types/react",
    "description": "TypeScript definitions for react",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-dom",
    "description": "React package for working with the DOM.",
    "keywords": [
      "react"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-redux",
    "description": "Official React bindings for Redux",
    "keywords": [
      "react",
      "reactjs",
      "redux"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "eslint-plugin-react",
    "description": "React specific linting rules for ESLint",
    "keywords": [
      "eslint",
      "eslint-plugin",
      "eslintplugin",
      "react"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "eslint-plugin-react-hooks",
    "description": "ESLint rules for React Hooks",
    "keywords": [
      "eslint",
      "eslint-plugin",
      "eslintplugin",
      "react"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@react-navigation/native",
    "description": "React Native integration for React Navigation",
    "keywords": [
      "react-native",
      "react-navigation",
      "ios",
      "android"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-draggable",
    "description": "React draggable component",
    "keywords": [
      "react",
      "draggable",
      "react-component"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-freeze",
    "description": "React Freeze",
    "keywords": [
      "react",
      "freeze"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@storybook/react",
    "description": "Storybook React renderer",
    "keywords": [
      "storybook"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@floating-ui/react-dom",
    "description": "Floating UI for React DOM",
    "keywords": [
      "tooltip",
      "popover",
      "dropdown",
      "menu",
      "popup",
      "positioning",
      "react",
      "react-dom"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@floating-ui/react",
    "description": "Floating UI for React",
    "keywords": [
      "tooltip",
      "popover",
      "dropdown",
      "menu",
      "popup",
      "positioning",
      "react",
      "react-dom"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@mdx-js/react",
    "description": "React context for MDX",
    "keywords": [
      "jsx",
      "markdown",
      "mdx",
      "react",
      "remark"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-markdown",
    "description": "React component to render markdown",
    "keywords": [
      "ast",
      "commonmark",
      "component",
      "gfm",
      "markdown",
      "react",
      "react-component",
      "remark",
      "unified"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-router-dom",
    "description": "Declarative routing for React web applications",
    "keywords": [
      "react",
      "router",
      "route",
      "routing",
      "history",
      "link"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-transition-group",
    "description": "A react component toolset for managing animations",
    "keywords": [
      "react",
      "transition",
      "addons",
      "transition-group",
      "animation",
      "css",
      "transitions"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-toastify",
    "description": "React notification made easy",
    "keywords": [
      "react",
      "notification",
      "toast",
      "react-component",
      "react-toastify",
      "push",
      "alert",
      "snackbar",
      "message"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@types/react-dom",
    "description": "TypeScript definitions for react-dom",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-refresh",
    "description": "React is a JavaScript library for building user interfaces.",
    "keywords": [
      "react"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@react-spring/web",
    "description": "`react-dom` support",
    "keywords": [
      "animated",
      "animation",
      "hooks",
      "motion",
      "react",
      "react-native",
      "spring",
      "typescript",
      "velocity"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-tooltip",
    "description": "react tooltip component",
    "keywords": [
      "react",
      "react-component",
      "tooltip",
      "react-tooltip"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "lucide-react",
    "description": "A Lucide icon library package for React applications.",
    "keywords": [
      "Lucide",
      "React",
      "Feather",
      "Icons",
      "Icon",
      "SVG",
      "Feather Icons",
      "Fontawesome",
      "Font Awesome"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@emotion/react",
    "description": "> Simple styling in React.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-test-renderer",
    "description": "React package for snapshot testing.",
    "keywords": [
      "react",
      "react-native",
      "react-testing"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "lottie-react",
    "description": "Lottie for React",
    "keywords": [
      "lottie",
      "react",
      "lottie react",
      "react lottie",
      "lottie web",
      "animation",
      "component",
      "hook"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@vitejs/plugin-react",
    "description": "The default Vite plugin for React projects",
    "keywords": [
      "vite",
      "vite-plugin",
      "react",
      "babel",
      "react-refresh",
      "fast refresh"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-popper-tooltip",
    "description": "React tooltip library built around react-popper",
    "keywords": [
      "react",
      "tooltip",
      "popover",
      "overlay",
      "react-tooltip",
      "react-popper"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "ui",
    "description": "platform agnostic ui models",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@floating-ui/utils",
    "description": "Utilities for Floating UI",
    "keywords": [
      "tooltip",
      "popover",
      "dropdown",
      "menu",
      "popup",
      "positioning"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@floating-ui/dom",
    "description": "Floating UI for the web",
    "keywords": [
      "tooltip",
      "popover",
      "dropdown",
      "menu",
      "popup",
      "positioning"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "swagger-ui-express",
    "description": "Swagger UI Express",
    "keywords": [
      "swagger",
      "express",
      "ui",
      "json",
      "documentation"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@vitest/ui",
    "description": "UI for Vitest",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@material-ui/system",
    "description": "Material-UI System - Design system for Material-UI.",
    "keywords": [
      "react",
      "react-component",
      "material design",
      "material-ui",
      "system"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@material-ui/types",
    "description": "Material-UI Types - Utility types for Material-UI.",
    "keywords": [
      "react",
      "react-component",
      "material design",
      "material-ui",
      "types"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@material-ui/utils",
    "description": "Material-UI Utils - Utility functions for Material-UI.",
    "keywords": [
      "react",
      "react-component",
      "material design",
      "material-ui",
      "utils"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@storybook/ui",
    "description": "Core Storybook UI",
    "keywords": [
      "storybook"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "swagger-ui-dist",
    "description": "[![NPM version](https://badge.fury.io/js/swagger-ui-dist.svg)](http://badge.fury.io/js/swagger-ui-dist)",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@ckeditor/ckeditor5-ui",
    "description": "The UI framework and standard UI library of CKEditor 5.",
    "keywords": [
      "ckeditor",
      "ckeditor5",
      "ckeditor 5",
      "ckeditor5-lib",
      "ckeditor5-dll"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "fizzy-ui-utils",
    "description": "UI utilities",
    "keywords": [
      "ui",
      "utility",
      "browser",
      "DOM"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@sanity/ui",
    "description": "The Sanity UI components.",
    "keywords": [
      "sanity",
      "ui",
      "primitives",
      "react",
      "components",
      "design-system"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@floating-ui/vue",
    "description": "Floating UI for Vue",
    "keywords": [
      "tooltip",
      "popover",
      "dropdown",
      "menu",
      "popup",
      "positioning",
      "vue"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@chakra-ui/control-box",
    "description": "Chakra UI ControlBox component",
    "keywords": [
      "checkbox",
      "custom",
      "input",
      "react",
      "chakra-ui"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@chakra-ui/system",
    "description": "Chakra UI system primitives",
    "keywords": [
      "system",
      "styled-component",
      "emotion",
      "ui-component",
      "ui",
      "chakra",
      "style-props",
      "design-system"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "expo-system-ui",
    "description": "Interact with system UI elements",
    "keywords": [
      "react-native",
      "expo",
      "background-color",
      "user-interface",
      "appearance"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "reka-ui",
    "description": "Vue port for Radix UI Primitives.",
    "keywords": [
      "ui",
      "vue",
      "accessibility",
      "headless",
      "nuxt",
      "primitives",
      "components",
      "radix",
      "unstyled"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@fastify/swagger-ui",
    "description": "Serve Swagger-ui for Fastify",
    "keywords": [
      "fastify",
      "swagger",
      "openapi",
      "swagger-ui",
      "serve",
      "static"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@radix-ui/react-icons",
    "description": "Radix UI React Icon Set",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "ra-ui-materialui",
    "description": "UI Components for react-admin with Material UI",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@types/swagger-ui-express",
    "description": "TypeScript definitions for swagger-ui-express",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@material-ui/icons",
    "description": "Material Design Svg Icons converted to Material-UI React components.",
    "keywords": [
      "react",
      "react-component",
      "material design",
      "material-ui",
      "icons"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@leafygreen-ui/typography",
    "description": "leafyGreen UI Kit Typography",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "instantsearch-ui-components",
    "description": "Common UI components for InstantSearch.",
    "keywords": [
      "algolia",
      "components",
      "fast",
      "instantsearch",
      "react",
      "search",
      "jsx",
      "vdom",
      "hyperscript"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@chakra-ui/css-reset",
    "description": "CSS reset component for Chakra UI",
    "keywords": [
      "theme",
      "theming",
      "ui mode",
      "chakra ui",
      "css reset"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@chakra-ui/table",
    "description": "Table component for React and Chakra UI",
    "keywords": [
      "react",
      "react component",
      "table",
      "accessible table",
      "a11y table",
      "react a11y table",
      "react accessible table",
      "react table",
      "chakra ui",
      "chakra",
      "react table component",
      "a11y",
      "react aria table",
      "aria",
      "aria table"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "swagger-ui-react",
    "description": "[![NPM version](https://badge.fury.io/js/swagger-ui-react.svg)](http://badge.fury.io/js/swagger-ui-react)",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@hapi/statehood",
    "description": "HTTP State Management Utilities",
    "keywords": [
      "HTTP",
      "state",
      "cookies",
      "secure"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "vuex",
    "description": "state management for Vue.js",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "mobx",
    "description": "Simple, scalable state management.",
    "keywords": [
      "mobx",
      "mobservable",
      "observable",
      "react-component",
      "react",
      "reactjs",
      "reactive",
      "model",
      "frp",
      "functional-reactive-programming",
      "state management",
      "data flow"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "little-state-machine",
    "description": "State management made super simple",
    "keywords": [
      "state",
      "flux"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@snap/state-management",
    "description": "Redux-inspired state management using Observables",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "recoil",
    "description": "Recoil - A state management library for React",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@segment/sovran-react-native",
    "description": "A cross-platform state management system",
    "keywords": [
      "react-native",
      "ios",
      "android",
      "segment"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@wordpress/notices",
    "description": "State management for notices.",
    "keywords": [
      "wordpress",
      "gutenberg",
      "notices"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "flowstate",
    "description": "Per-request state management middleware.",
    "keywords": [
      "express",
      "connect",
      "state"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "simpler-state",
    "description": "The simplest app state management for React",
    "keywords": [
      "react",
      "state",
      "global",
      "shared",
      "data",
      "simple",
      "functional",
      "hooks"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "mobx-react-form",
    "description": "Reactive MobX Form State Management",
    "keywords": [
      "form",
      "mobx",
      "state",
      "events",
      "nested",
      "fields",
      "bindings",
      "react",
      "reactive",
      "validation",
      "validator",
      "json",
      "schema",
      "declarative",
      "rules"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@antv/data-set",
    "description": "data set with state management",
    "keywords": [
      "antv",
      "data-set",
      "dataSet"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@ngneat/elf",
    "description": "A reactive state management for JS applications",
    "keywords": [
      "rxjs",
      "state management",
      "reactive state management",
      "js state management",
      "reactive store",
      "elf"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@datorama/akita",
    "description": "A Reactive State Management Tailored-Made for JS Applications",
    "keywords": [
      "angular",
      "state management",
      "react",
      "vue",
      "typescript",
      "javascript",
      "rxjs",
      "angular store",
      "store",
      "observable data stores",
      "redux",
      "reactive"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "final-form",
    "description": "🏁 Framework agnostic, high performance, subscription-based form state management",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-final-form",
    "description": "🏁 High performance subscription-based form state management for React",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@chatscope/use-chat",
    "description": "React hook for state management in chat applications",
    "keywords": [
      "chat",
      "headless",
      "hook",
      "react",
      "reactjs",
      "ui",
      "user interface",
      "components",
      "ui kit",
      "communication",
      "conversation",
      "toolkit",
      "library",
      "frontend",
      "reusable",
      "social",
      "talk"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "overmind",
    "description": "Frictionless state management",
    "keywords": [
      "state",
      "sideeffects",
      "app",
      "framework"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "next-query-params",
    "description": "Convenient state management of query parameters in Next.js apps.",
    "keywords": [
      "react",
      "next",
      "url",
      "query",
      "parameters",
      "hook",
      "hooks"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "alvamind",
    "description": "A lightweight state management library",
    "keywords": [
      "state-management",
      "typescript"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@tcn/state",
    "description": "State management for complex business logic.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@openmrs/esm-state",
    "description": "Frontend stores & state management for OpenMRS",
    "keywords": [
      "openmrs",
      "microfrontends"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-native-onyx",
    "description": "State management for React Native",
    "keywords": [
      "React Native",
      "React",
      "Persistent storage",
      "Pub/Sub"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@storefront/flux-capacitor",
    "description": "State management for StoreFront",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-oidc-context",
    "description": "OpenID Connect & OAuth2 authentication using react context api as state management",
    "keywords": [
      "authentication",
      "context-api",
      "oauth2",
      "oidc",
      "openid",
      "OpenID Connect",
      "react-component"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "unstated-next",
    "description": "200 bytes to never think about React state management libraries ever again",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@opentelemetry/instrumentation-dataloader",
    "description": "OpenTelemetry instrumentation for `dataloader` data fetching layer",
    "keywords": [
      "dataloader",
      "instrumentation",
      "nodejs",
      "opentelemetry",
      "profiling",
      "tracing"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "sswr",
    "description": "Svelte stale while revalidate (SWR) data fetching strategy",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "swrev",
    "description": "Framework agnostic stale while revalidate (SWR) data fetching strategy",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "swr-store",
    "description": "SWR stores for data-fetching",
    "keywords": [
      "pridepack",
      "swr"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@pinia/colada",
    "description": "The smart data fetching layer for Vue.js",
    "keywords": [
      "pinia",
      "plugin",
      "data",
      "fetching",
      "query",
      "mutation",
      "cache",
      "layer"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "dexie-react-hooks",
    "description": "React hooks for reactive data fetching using Dexie.js",
    "keywords": [
      "react",
      "hooks",
      "indexeddb",
      "storage",
      "data-fetching",
      "reactive",
      "subscription",
      "dexie"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "use-asset",
    "description": "A data fetching strategy for React Suspense",
    "keywords": [
      "react",
      "suspense",
      "resource",
      "asset"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-async",
    "description": "React component for declarative promise resolution and data fetching",
    "keywords": [
      "react",
      "async",
      "promise",
      "fetch",
      "hook"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "thwack",
    "description": "A tiny modern data fetching solution.",
    "keywords": [
      "utils",
      "lib",
      "fetch",
      "axios",
      "xmlhttprequest",
      "xhr",
      "http",
      "ajax",
      "promise",
      "nodejs",
      "react-native"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@nanostores/query",
    "description": "Tiny remote data fetching library for Nano Stores",
    "keywords": [
      "nano",
      "react",
      "react-native",
      "preact",
      "vue",
      "svelte",
      "store",
      "request",
      "cache",
      "fetch"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-resolver",
    "description": "Async-rendering & data-fetching for universal React applications",
    "keywords": [
      "async",
      "decorator",
      "lazy",
      "load",
      "react",
      "resolve"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "use-async-resource",
    "description": "A custom React hook for simple data fetching with React Suspense",
    "keywords": [
      "react",
      "reactjs",
      "async",
      "data",
      "fetch",
      "cache",
      "suspense",
      "hooks",
      "custom-hook",
      "react-hook",
      "react-hooks",
      "react-cache",
      "react-suspense",
      "data-fetching"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@dhis2/app-service-data",
    "description": "Declarative data fetching for [DHIS2](https://dhis2.org) applications",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "mutoid",
    "description": "Reactive library for data fetching, caching, state management",
    "keywords": [
      "algebraic-data-types",
      "fp-ts-rxjs",
      "fp-ts",
      "io-ts",
      "isomorphic",
      "react",
      "reactive",
      "reactivex",
      "rxjs",
      "typescript"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@normy/core",
    "description": "Automatic normalization and data updates for data fetching libraries",
    "keywords": [
      "normalization",
      "react-query"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "join-monster",
    "description": "A GraphQL to SQL query execution layer for batch data fetching.",
    "keywords": [
      "graphql",
      "sql",
      "join",
      "query",
      "batch",
      "data",
      "schema"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "redial",
    "description": "Universal data fetching and route lifecycle management for React etc.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-data-fetching",
    "description": "Declarative data fetching for React",
    "keywords": [
      "react",
      "native",
      "data",
      "fetch",
      "api",
      "component"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@normy/react-query",
    "description": "react-query addon for normy - automatic normalization and data updates for data fetching libraries",
    "keywords": [
      "normalization",
      "react-query"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "expect-puppeteer",
    "description": "Assertion toolkit for Puppeteer.",
    "keywords": [
      "jest",
      "puppeteer",
      "jest-puppeteer",
      "chromeless",
      "chrome-headless",
      "expect",
      "assert",
      "should",
      "assertion"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "puppeteer-extra",
    "description": "Teach puppeteer new tricks through plugins.",
    "keywords": [
      "puppeteer",
      "puppeteer-extra",
      "flash",
      "stealth",
      "prefs",
      "user-preferences",
      "chrome",
      "headless",
      "pupeteer"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "jest-environment-puppeteer",
    "description": "Puppeteer environment for Jest.",
    "keywords": [
      "jest",
      "jest-environment",
      "puppeteer",
      "jest-puppeteer",
      "chromeless",
      "chrome-headless"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "puppeteer-extra-plugin",
    "description": "Base class for puppeteer-extra plugins.",
    "keywords": [
      "puppeteer",
      "puppeteer-extra",
      "puppeteer-extra-plugin",
      "ua",
      "user-agent",
      "chrome",
      "headless",
      "pupeteer"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "puppeteer-cluster",
    "description": "Cluster management for puppeteer",
    "keywords": [
      "puppeteer",
      "cluster",
      "pool"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "jest-puppeteer",
    "description": "Run your tests using Jest & Puppeteer.",
    "keywords": [
      "jest",
      "puppeteer",
      "jest-puppeteer",
      "chromeless",
      "chrome-headless"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "puppeteer-extra-plugin-user-preferences",
    "description": "Launch puppeteer with arbitrary user preferences.",
    "keywords": [
      "puppeteer",
      "puppeteer-extra",
      "puppeteer-extra-plugin",
      "user-prefs",
      "user-preferences",
      "chrome",
      "headless",
      "pupeteer"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "puppeteer-extra-plugin-user-data-dir",
    "description": "Custom user data directory for puppeteer.",
    "keywords": [
      "puppeteer",
      "puppeteer-extra",
      "puppeteer-extra-plugin",
      "user-data",
      "userDataDir",
      "profile",
      "chrome",
      "headless",
      "pupeteer"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "puppeteer-har",
    "description": "Generate HAR file with Puppeteer",
    "keywords": [
      "har",
      "puppeteer",
      "performance"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@applitools/eyes-puppeteer",
    "description": "Applitools Eyes SDK for Puppeteer",
    "keywords": [
      "eyes-puppeteer",
      "applitools",
      "eyes",
      "test automation",
      "visual regression",
      "automation",
      "testing",
      "tests",
      "puppeteer"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "puppeteer-extra-plugin-stealth",
    "description": "Stealth mode: Applies various techniques to make detection of headless puppeteer harder.",
    "keywords": [
      "puppeteer",
      "puppeteer-extra",
      "puppeteer-extra-plugin",
      "stealth",
      "stealth-mode",
      "detection-evasion",
      "crawler",
      "chrome",
      "headless",
      "pupeteer"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@types/jest-environment-puppeteer",
    "description": "TypeScript definitions for jest-environment-puppeteer",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@types/expect-puppeteer",
    "description": "TypeScript definitions for expect-puppeteer",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "vitest-environment-puppeteer",
    "description": "Puppeteer environment for Vitest.",
    "keywords": [
      "vitest",
      "vitest-environment",
      "puppeteer",
      "vitest-puppeteer",
      "chromeless",
      "chrome-headless"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@hint/connector-puppeteer",
    "description": "hint connector for browsers supported by Puppeteer",
    "keywords": [
      "connector",
      "chromium",
      "edge",
      "microsoft edge",
      "chrome",
      "google chrome",
      "hint",
      "hint-connector-puppeteer",
      "puppeteer",
      "webhint"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "puppeteer-extra-plugin-adblocker",
    "description": "A puppeteer-extra plugin to block ads and trackers.",
    "keywords": [
      "puppeteer",
      "puppeteer-extra",
      "puppeteer-extra-plugin",
      "ads",
      "adblocker",
      "adblocking"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@cypress/puppeteer",
    "description": "Plugin for enhancing Cypress tests with Puppeteer",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "puppeteer-extra-plugin-recaptcha",
    "description": "A puppeteer-extra plugin to solve reCAPTCHAs and hCaptchas automatically.",
    "keywords": [
      "puppeteer",
      "puppeteer-extra",
      "puppeteer-extra-plugin",
      "recaptcha",
      "hcaptcha",
      "captcha",
      "2captcha"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@axe-core/puppeteer",
    "description": "Provides a chainable axe API for Puppeteer and automatically injects into all frames",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "puppeteer-extra-plugin-anonymize-ua",
    "description": "Anonymize User-Agent in puppeteer.",
    "keywords": [
      "puppeteer",
      "puppeteer-extra",
      "puppeteer-extra-plugin",
      "ua",
      "user-agent",
      "chrome",
      "headless",
      "pupeteer"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@ghostery/adblocker-puppeteer",
    "description": "Ghostery adblocker Puppeteer wrapper",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "pptr-testing-library",
    "description": "puppeteer + dom-testing-library",
    "keywords": [
      "puppeteer",
      "dom-testing-library",
      "testing-library",
      "testing",
      "utility"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@web/test-runner-puppeteer",
    "description": "Puppeteer browser launcher for Web Test Runner",
    "keywords": [
      "web",
      "test",
      "runner",
      "testrunner",
      "puppeteer",
      "browser",
      "launcher"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@types/aws-synthetics-puppeteer",
    "description": "TypeScript definitions for aws-synthetics-puppeteer",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "nestjs-puppeteer",
    "description": "Puppeteer module for NestJS",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "puppeteer-extra-plugin-proxy",
    "description": "A puppeteer-extra plugin to add convenient proxy support to puppeteer",
    "keywords": [
      "puppeteer",
      "puppeteer-extra",
      "puppeteer-extra-plugin",
      "proxy",
      "chrome",
      "headless",
      "authless"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "puppeteer-autoscroll-down",
    "description": "Handle infinite scroll on websites with puppeteer",
    "keywords": [
      "headless-chrome",
      "puppeteer",
      "parsing",
      "infinite",
      "scroll"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@wordpress/jest-puppeteer-axe",
    "description": "Axe API integration with Jest and Puppeteer.",
    "keywords": [
      "wordpress",
      "gutenberg",
      "jest",
      "puppeteer",
      "axe",
      "accessibility"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "puppeteer-mcp-server",
    "description": "Experimental MCP server for browser automation using Puppeteer (inspired by @modelcontextprotocol/server-puppeteer)",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@mapbox/vector-tile",
    "description": "Parses vector tiles",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@types/react-native-vector-icons",
    "description": "TypeScript definitions for react-native-vector-icons",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "geojson-vt",
    "description": "Slice GeoJSON data into vector tiles efficiently",
    "keywords": [
      "spatial",
      "geojson",
      "tiles",
      "geometry"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "filtered-vector",
    "description": "Filter an input vector valued curve",
    "keywords": [
      "filter",
      "input",
      "curve",
      "device",
      "mouse"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "term-vector",
    "description": "Creates a term vector from tokenized text.",
    "keywords": [
      "natural",
      "language",
      "vector",
      "vector space model"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "esri-leaflet-vector",
    "description": "Esri vector basemap and vector tile layer plugin for Leaflet.",
    "keywords": [
      "maplibre",
      "arcgis",
      "leaflet",
      "leafletjs",
      "maps"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "raphael",
    "description": "JavaScript Vector Library",
    "keywords": [
      "svg",
      "vml",
      "javascript"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "vt-pbf",
    "description": "Serialize mapbox vector tiles to binary protobufs in javascript.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@loaders.gl/mvt",
    "description": "Loader for Mapbox Vector Tiles",
    "keywords": [
      "geometry",
      "loader",
      "parser",
      "MVT",
      "Mapbox Vector Tiles"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "art",
    "description": "Cross-browser Vector Graphics",
    "keywords": [
      "art",
      "canvas",
      "svg",
      "vml"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@upstash/vector",
    "description": "An HTTP/REST based Vector DB client built on top of Upstash REST API.",
    "keywords": [
      "vector",
      "upstash",
      "db"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "gl-matrix",
    "description": "Javascript Matrix and Vector library for High Performance WebGL apps",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@expo/vector-icons",
    "description": "Built-in support for popular icon fonts and the tooling to create your own Icon components from your font and glyph map. This is a wrapper around react-native-vector-icons to make it compatible with Expo.",
    "keywords": [
      "expo"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "country-flag-icons",
    "description": "Vector (*.svg) country flag icons in 3x2 aspect ratio.",
    "keywords": [
      "country",
      "flag",
      "icons",
      "vector",
      "svg",
      "react"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "svgo",
    "description": "SVGO is a Node.js library and command-line application for optimizing vector images.",
    "keywords": [
      "svgo",
      "svg",
      "optimize",
      "minify"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "jqvmap-novulnerability",
    "description": "jQuery Vector Map Library",
    "keywords": [
      "jquery",
      "map",
      "svg",
      "vml",
      "vector"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@react-native-vector-icons/ionicons",
    "description": "Ionicons font for react native vector icons",
    "keywords": [
      "react-native",
      "ios",
      "android",
      "osx",
      "windows",
      "macos",
      "react-component",
      "react-native-component",
      "react",
      "mobile",
      "ui",
      "icon",
      "icons",
      "vector",
      "retina",
      "font",
      "react-native-vector-icons-icon",
      "ionicons"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@react-native-vector-icons/material-design-icons",
    "description": "Material Design Icons font for react native vector icons",
    "keywords": [
      "react-native",
      "ios",
      "android",
      "osx",
      "windows",
      "macos",
      "react-component",
      "react-native-component",
      "react",
      "mobile",
      "ui",
      "icon",
      "icons",
      "vector",
      "retina",
      "font",
      "react-native-vector-icons-icon",
      "material-design-icons"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-native-vector-image",
    "description": "Native vector images generated from SVG",
    "keywords": [
      "react-native",
      "image",
      "svg",
      "vector"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "leaflet-draw",
    "description": "Vector drawing plugin for Leaflet",
    "keywords": [
      "maps",
      "leaflet",
      "client",
      "vector",
      "drawing",
      "draw"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@react-native-vector-icons/material-icons",
    "description": "Material Icons font for react native vector icons",
    "keywords": [
      "react-native",
      "ios",
      "android",
      "osx",
      "windows",
      "macos",
      "react-component",
      "react-native-component",
      "react",
      "mobile",
      "ui",
      "icon",
      "icons",
      "vector",
      "retina",
      "font",
      "react-native-vector-icons-icon",
      "material-icons"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@langchain/qdrant",
    "description": "LangChain.js integration for the Qdrant vector database",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "paper",
    "description": "The Swiss Army Knife of Vector Graphics Scripting",
    "keywords": [
      "vector",
      "graphic",
      "graphics",
      "2d",
      "geometry",
      "bezier",
      "curve",
      "curves",
      "path",
      "paths",
      "canvas",
      "svg",
      "paper",
      "paper.js",
      "paperjs"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "rat-vec",
    "description": "Exact rational vector arithmetic",
    "keywords": [
      "rational",
      "vector",
      "exact",
      "arithmetic",
      "geometry"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@brightlayer-ui/react-native-vector-icons",
    "description": "Brightlayer UI vector icons for use in React Native projects, based on react-native-vector-icons",
    "keywords": [
      "react-native",
      "Brightlayer UI",
      "brightlayer-ui",
      "icons",
      "vector",
      "power",
      "eaton"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "snapsvg",
    "description": "JavaScript Vector Library",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@react-native-vector-icons/fontawesome",
    "description": "Fontawesome font for react native vector icons",
    "keywords": [
      "react-native",
      "ios",
      "android",
      "osx",
      "windows",
      "macos",
      "react-component",
      "react-native-component",
      "react",
      "mobile",
      "ui",
      "icon",
      "icons",
      "vector",
      "retina",
      "font",
      "react-native-vector-icons-icon",
      "fontawesome"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@react-native-vector-icons/feather",
    "description": "Feather font for react native vector icons",
    "keywords": [
      "react-native",
      "ios",
      "android",
      "osx",
      "windows",
      "macos",
      "react-component",
      "react-native-component",
      "react",
      "mobile",
      "ui",
      "icon",
      "icons",
      "vector",
      "retina",
      "font",
      "react-native-vector-icons-icon",
      "feather"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@traceloop/instrumentation-pinecone",
    "description": "OpenTelemetry instrumentation for pinecone vector DB",
    "keywords": [
      "opentelemetry",
      "nodejs",
      "tracing",
      "attributes",
      "semantic conventions"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@upstash/semantic-cache",
    "description": "A Semantic cache built on top of Upstash Vector DB",
    "keywords": [
      "vector",
      "upstash",
      "db",
      "semantic-cache",
      "cache",
      "classification"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "mime-db",
    "description": "Media Type Database",
    "keywords": [
      "mime",
      "db",
      "type",
      "types",
      "database",
      "charset",
      "charsets"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "update-browserslist-db",
    "description": "CLI tool to update caniuse-lite to refresh target browsers from Browserslist config",
    "keywords": [
      "caniuse",
      "browsers",
      "target"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@datastax/astra-db-ts",
    "description": "Data API TypeScript client",
    "keywords": [
      "astra",
      "cassandra",
      "dse",
      "document",
      "model",
      "schema",
      "database",
      "data",
      "datastore",
      "query",
      "nosql",
      "orm",
      "db",
      "dataapi"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "mime-types",
    "description": "The ultimate javascript content-type utility.",
    "keywords": [
      "mime",
      "types"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@mastra/pg",
    "description": "Postgres provider for Mastra - includes both vector and db storage capabilities",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@lancedb/lancedb",
    "description": "LanceDB: A serverless, low-latency vector database for AI applications",
    "keywords": [
      "database",
      "lance",
      "lancedb",
      "search",
      "vector",
      "vector database",
      "ann"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "mapbox-gl",
    "description": "A WebGL interactive maps library",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "ml-nearest-vector",
    "description": "Find the nearest point to a sample point",
    "keywords": [
      "machine",
      "learning",
      "data",
      "mining",
      "datamining",
      "nearest",
      "vector",
      "cluster"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "imvectordb",
    "description": "A super simple in-memory VectorDB",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@react-native-vector-icons/common",
    "description": "Customizable Icons for React Native with support for image source and full styling.",
    "keywords": [
      "react-native",
      "ios",
      "android",
      "osx",
      "windows",
      "macos",
      "react-component",
      "react-native-component",
      "react",
      "mobile",
      "ui",
      "icon",
      "icons",
      "vector",
      "retina",
      "font"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "caniuse-lite",
    "description": "A smaller version of caniuse-db, with only the essentials!",
    "keywords": [
      "support"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@azure/cosmos",
    "description": "Microsoft Azure Cosmos DB Service Node.js SDK for NOSQL API",
    "keywords": [
      "cosmosdb",
      "cosmos db",
      "documentdb",
      "document database",
      "azure",
      "nosql",
      "database",
      "cloud",
      "azure"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "sat",
    "description": "Library for performing 2D collision detection",
    "keywords": [
      "collision detection",
      "sat",
      "game"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@llm-ui/markdown",
    "description": "[llm-ui](https://llm-ui.com) markdown block.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@llm-ui/code",
    "description": "[llm-ui](https://llm-ui.com) code block.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "llm-cost",
    "description": "[![Tests](https://github.com/rogeriochaves/llm-cost/actions/workflows/node.js.yml/badge.svg)](https://github.com/rogeriochaves/llm-cost/actions/workflows/node.js.yml) [![npm version](https://badge.fury.io/js/llm-cost.svg)](https://www.npmjs.com/package/ll",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "llm-chunk",
    "description": "A super simple text splitter for LLM",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "easy-llm-cli",
    "description": "![Easy LLM CLI 截图](./docs/assets/openrouter.png)",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "partial-json",
    "description": "Parse partial JSON generated by LLM",
    "keywords": [
      "JSON",
      "parser",
      "LLM",
      "nlp"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "langsmith",
    "description": "Client library to connect to the LangSmith LLM Tracing and Evaluation Platform.",
    "keywords": [
      "LLM",
      "Tracing",
      "Evaluation",
      "LangChain"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "promptfoo",
    "description": "LLM eval & testing toolkit",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "llm-agents",
    "description": "LLM Agent framework for Node.js",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@llm-ui/json",
    "description": "[llm-ui](https://llm-ui.com) JSON blocks for building custom components.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@empiricalrun/llm",
    "description": "Package to connect and trace LLM calls.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@musistudio/llms",
    "description": "A universal LLM API transformation server",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@lobehub/icons",
    "description": "Popular AI / LLM Model Brand SVG Logo and Icon Collection",
    "keywords": [
      "lobehub",
      "llm icons",
      "llm brand logo",
      "react components",
      "svg icons"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@vscode/prompt-tsx",
    "description": "Declare LLM prompts with TSX",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@arizeai/openinference-semantic-conventions",
    "description": "This package provides OpenInference semantic conventions for tracing of LLM Applications.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "llm-code-highlighter",
    "description": "Condense source code for LLM analysis by extracting essential highlights, utilizing a simplified version of Paul Gauthier's repomap technique from Aider Chat.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "langbase",
    "description": "The AI SDK for building declarative and composable AI-powered LLM products.",
    "keywords": [
      "ai",
      "llm",
      "langbase core",
      "langbase sdk",
      "baseai",
      "base ai",
      "langbase",
      "langbase.com",
      "generative AI"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@llamaindex/chat-ui",
    "description": "Chat UI components for LLM apps",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@getzep/zep-cloud",
    "description": "Zep: Fast, scalable building blocks for production LLM apps",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@getzep/zep-js",
    "description": "Zep: Fast, scalable building blocks for production LLM apps",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-chatbot-kit",
    "description": "Fully customizable chatbot kit for react.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-simple-chatbot",
    "description": "React Simple Chatbot",
    "keywords": [
      "react",
      "chat",
      "chatbot",
      "conversational-ui"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "discord-chatbot",
    "description": "A simple Chatbot for your Discord bot",
    "keywords": [
      "chatbot",
      "discord.js",
      "discord",
      "bot",
      "ai",
      "ai",
      "chatbot"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "react-driftjs",
    "description": "React component implementation of Drift Chatbot Widget",
    "keywords": [
      "React",
      "Drift",
      "npm"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "flowise-embed",
    "description": "Javascript library to display flowise chatbot on your website",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@quickstart-ai/chatbot",
    "description": "Chatbot React",
    "keywords": [
      "chatbot",
      "react",
      "typescript",
      "npm",
      "AI chatbot",
      "react component",
      "customer support",
      "chatbot integration",
      "business chatbot",
      "customer service",
      "automated responses",
      "react hooks",
      "styled-components",
      "tailwindcss",
      "vite",
      "open source",
      "AI",
      "react chatbot",
      "frontend",
      "react development",
      "react library",
      "react chatbot component",
      "react chatbot ui",
      "react chatbot widget",
      "simple installtion chatbot",
      "chatbot for website",
      "token based chatbot",
      "chatbot for business",
      "chatbot for customer service",
      "chatbot for customer support",
      "chatbot for customer interaction",
      "script chatbot"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@chatui/core",
    "description": "The React library for Chatbot UI",
    "keywords": [
      "react",
      "react-component",
      "chat",
      "chat-ui"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@eeacms/volto-chatbot",
    "description": "@eeacms/volto-chatbot: Volto add-on",
    "keywords": [
      "volto-addon",
      "volto",
      "plone",
      "react"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "flowise-embed-react",
    "description": "React library to display flowise chatbot on your website",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@virtuoso.dev/message-list",
    "description": "Virtualized React component for rendering human/AI chatbot conversations.",
    "keywords": [
      "react",
      "virtual",
      "message list",
      "endless scrolling",
      "list",
      "scrolling",
      "infinite",
      "virtualized",
      "chat",
      "chatbot"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "wechaty",
    "description": "Wechaty is a RPA SDK for Chatbot Makers.",
    "keywords": [
      "ai",
      "bot",
      "chatbot",
      "chatie",
      "conversational",
      "framework",
      "robotics",
      "robot",
      "rpa",
      "sdk",
      "wechat",
      "wecom",
      "wxwork",
      "lark",
      "TikTok",
      "weixin",
      "whatsapp",
      "微信"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@firebase/database-types",
    "description": "@firebase/database Types",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@firebase/database-compat",
    "description": "The Realtime Database component of the Firebase JS SDK.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@firebase/database",
    "description": "This is the Firebase Realtime Database component of the Firebase JS SDK.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@strapi/database",
    "description": "Strapi's database layer",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@planetscale/database",
    "description": "A Fetch API-compatible PlanetScale database driver",
    "keywords": [
      "planetscale",
      "database",
      "mysql",
      "vitess",
      "serverless",
      "vercel",
      "lambda"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "parse-database-url",
    "description": "Database configuration URL parser for node.js",
    "keywords": [
      "database",
      "configuration",
      "url",
      "heroku",
      "database_url"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@hapi/mimos",
    "description": "Mime database interface",
    "keywords": [
      "mime",
      "database",
      "content-type"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "ts-parse-database-url",
    "description": "Parse database urls",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "oci-database",
    "description": "OCI NodeJS client for Database",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@hocuspocus/extension-database",
    "description": "a generic Hocuspocus persistence driver for the database",
    "keywords": [
      "hocuspocus",
      "yjs"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "all.db",
    "description": "JSON Database",
    "keywords": [
      "Simple",
      "Fast",
      "JSON Database"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@replit/database",
    "description": "Client for Repl.it Database",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@supabase/realtime-js",
    "description": "Listen to realtime updates to your PostgreSQL database",
    "keywords": [
      "realtime",
      "phoenix",
      "elixir",
      "javascript",
      "typescript",
      "firebase",
      "supabase"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@cloudbase/database",
    "description": "database for (node.)js sdk ",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@sap/hana-database-explorer",
    "description": "SAP HANA Database Explorer for Visual Studio Code package",
    "keywords": [
      "hana-tooling"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@cap-js/db-service",
    "description": "CDS base database service",
    "keywords": [
      "CAP",
      "CDS"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "hdb",
    "description": "SAP HANA Database Client for Node",
    "keywords": [
      "sap",
      "hana",
      "database",
      "in-memory"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "database-js",
    "description": "Common database interface for JavaScript",
    "keywords": [
      "database-js",
      "database-js-mysql",
      "database-js-postgres",
      "database-js-sqlite",
      "database-js-adodb",
      "database-js-firebase",
      "database-js-ini",
      "database-js-xlsx",
      "database-js-csv",
      "database-js-json",
      "javascript",
      "database",
      "db",
      "sql",
      "query",
      "driver",
      "mysql",
      "postgre",
      "postgres",
      "postgresql",
      "sqlite",
      "ado",
      "adodb",
      "firebase",
      "ini",
      "xls",
      "xlsx",
      "csv",
      "json"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@cap-js/sqlite",
    "description": "CDS database service for SQLite",
    "keywords": [
      "CAP",
      "CDS",
      "SQLite"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "database-cleaner",
    "description": "Database Cleaner for node.js",
    "keywords": [
      "database",
      "cleaner",
      "mongodb",
      "redis",
      "couchdb",
      "tests",
      "package.json",
      "elasticsearch"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "lokijs",
    "description": "Fast document oriented javascript in-memory database",
    "keywords": [
      "javascript",
      "document-oriented",
      "mmdb",
      "json",
      "nosql",
      "lokijs",
      "in-memory",
      "indexeddb"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "y-indexeddb",
    "description": "IndexedDB database adapter for Yjs",
    "keywords": [
      "Yjs",
      "CRDT",
      "offline",
      "shared editing",
      "collaboration",
      "concurrency"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@aws-sdk/client-database-migration-service",
    "description": "AWS SDK for JavaScript Database Migration Service Client for Node.js, Browser and React Native",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "y-leveldb",
    "description": "LevelDb database adapter for Yjs",
    "keywords": [
      "Yjs",
      "CRDT",
      "offline",
      "shared editing",
      "collaboration",
      "concurrency"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "migrate-mongo",
    "description": "A database migration tool for MongoDB in Node",
    "keywords": [
      "migrate mongo mongodb migrations database"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@tursodatabase/database",
    "description": "The Turso database library",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "wordnet-db",
    "description": "WordNet 3.1 Database files",
    "keywords": [
      "WordNet",
      "wordpos",
      "natural",
      "pos"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@opentelemetry/instrumentation-mongodb",
    "description": "OpenTelemetry instrumentation for `mongodb` database client for MongoDB",
    "keywords": [
      "mongodb",
      "nodejs",
      "opentelemetry",
      "plugin",
      "profiling",
      "tracing"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "analytics",
    "description": "Lightweight analytics library for tracking events, page views, & identifying users. Works with any third party analytics provider via an extendable plugin system.",
    "keywords": [
      "analytics",
      "analytics-project",
      "metrics",
      "telemetry",
      "tracking",
      "event tracking",
      "page tracking",
      "user tracking",
      "custom events",
      "stats",
      "statistics",
      "monitoring",
      "pageviews"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@firebase/analytics-types",
    "description": "@firebase/analytics Types",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "analytics-utils",
    "description": "Analytics utility functions used by 'analytics' module",
    "keywords": [
      "analytics",
      "analytics-project",
      "analytics-utilities"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@firebase/analytics",
    "description": "A analytics package for new firebase packages",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@algolia/client-analytics",
    "description": "JavaScript client for client-analytics",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@analytics/google-analytics",
    "description": "Google analytics v4 plugin for 'analytics' module",
    "keywords": [
      "analytics",
      "analytics-project",
      "analytics-plugin",
      "GA",
      "google-analytics",
      "Google Analytics"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@segment/analytics-core",
    "description": "This package represents core 'shared' functionality that is shared by analytics packages. This is not designed to be used directly, but internal to analytics-node and analytics-browser.",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "universal-analytics",
    "description": "A node module for Google's Universal Analytics tracking",
    "keywords": [
      "google",
      "analytics",
      "universal",
      "tracking"
    ],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@aws-amplify/analytics",
    "description": "Analytics category of aws-amplify",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "@segment/analytics-node",
    "description": "https://www.npmjs.com/package/@segment/analytics-node",
    "keywords": [],
    "language": "javascript",
    "packageManager": "npm",
    "ecosystem": "node"
  },
  {
    "name": "requests",
    "description": "Python HTTP for Humans.",
    "keywords": [],
    "language": "python",
    "packageManager": "pip",
    "ecosystem": "python"
  },
  {
    "name": "pytest",
    "description": "pytest: simple powerful testing with Python",
    "keywords": [
      "test,",
      "unittest"
    ],
    "language": "python",
    "packageManager": "pip",
    "ecosystem": "python"
  },
  {
    "name": "poetry",
    "description": "Python dependency management and packaging made easy.",
    "keywords": [
      "packaging,",
      "dependency,",
      "poetry"
    ],
    "language": "python",
    "packageManager": "pip",
    "ecosystem": "python"
  },
  {
    "name": "Flask",
    "description": "A simple framework for building complex web applications.",
    "keywords": [],
    "language": "python",
    "packageManager": "pip",
    "ecosystem": "python"
  },
  {
    "name": "Django",
    "description": "A high-level Python web framework that encourages rapid development and clean, pragmatic design.",
    "keywords": [],
    "language": "python",
    "packageManager": "pip",
    "ecosystem": "python"
  }
] as const;

export default TOOL_CATALOG;
